// dizionario.mjs — tutte le parole del sito, in due colonne.
//
//     'chiave': ['English', 'Italiano'],
//
// LE DUE LINGUE STANNO SULLA STESSA RIGA, e la forma e' il controllo: una coppia non
// puo' avere una chiave in piu' di qua e una in meno di la'. Un dizionario per lingua —
// due file, due elenchi — si disallinea alla terza modifica e nessuno se ne accorge
// finche' qualcuno non legge la pagina in quella lingua. Qui il disallineamento non e'
// rappresentabile: o la riga c'e' con tutt'e due, o non c'e'.
//
// L'INGLESE E' LA SORGENTE (vedi lingua.mjs). Quello che sta nella prima colonna e'
// anche quello che sta scritto nell'HTML delle pagine: se i due divergono, il sito
// inglese dice una cosa e il dizionario un'altra — `test_lingua.mjs` guarda anche questo.
//
// I `{nome}` sono i buchi da riempire: t('com.giro', { n: 12 }). Il numero non si
// incolla dentro la frase perche' l'ordine delle parole cambia da una lingua all'altra.
//
// COSA NON STA QUI: i nomi propri (piloti, squadre, circuiti), le sigle (SOFT, VSC,
// P1), i numeri e i titoli degli articoli. Non sono interfaccia.
export const D = {

  /* ============================================================ il guscio */
  'nav.season':        ['Season',       'Stagione'],
  'nav.live':          ['Live',         'Live'],
  'nav.analysis':      ['Analysis',     'Analisi'],
  'nav.articles':      ['Articles',     'Articoli'],
  'nav.telemetry':     ['Telemetry',    'Telemetria'],
  'nav.championship':  ['Championship', 'Campionato'],

  'guscio.home':       ['Muretto Box Virtuale — home', 'Muretto Box Virtuale — home'],
  'guscio.sezioni':    ['Sections', 'Sezioni'],
  'guscio.piede_sott': ['SEASON 2026', 'STAGIONE 2026'],
  'guscio.piede_riga': ['Formula 1 2026 · replay, strategy and telemetry',
                        'Formula 1 2026 · replay, strategia e telemetria'],
  'guscio.segnala':    ['Report a problem', 'Segnala un problema'],

  'lingua.scegli':     ['Language', 'Lingua'],

  /* ------------------------------------------------------------ muro.mjs */
  'muro.guasto':       ['This data did not arrive. It may be the network.',
                        'Questi dati non sono arrivati. Può essere la rete.'],
  'muro.riprova':      ['Try again', 'Riprova'],
  'muro.non_raggiungibile': ['data not reachable: {url}', 'dato non raggiungibile: {url}'],

  /* --------------------------------------------------------- le mescole */
  // I nomi lunghi delle gomme. La SIGLA (SOFT/MEDIUM/HARD) non si traduce: e' quella
  // che sta scritta sul fianco della gomma e nei fogli FIA, in tutte le lingue.
  'mescola.SOFT':         ['soft',         'morbida'],
  'mescola.MEDIUM':       ['medium',       'media'],
  'mescola.HARD':         ['hard',         'dura'],
  'mescola.INTERMEDIATE': ['intermediate', 'intermedia'],
  'mescola.WET':          ['wet',          'da bagnato'],

  /* ------------------------------------------------------ parole comuni */
  'com.giro':          ['lap {n}',   'giro {n}'],
  'com.giri_n':        ['{n} laps',  '{n} giri'],
  'com.giro_1':        ['{n} lap',   '{n} giro'],
  'com.gara':          ['Race',      'Gara'],
  'com.pilota':        ['Driver',    'Pilota'],
  'com.squadra':       ['Team',      'Squadra'],
  'com.gare':          ['Races',     'Gare'],
  'com.round':         ['ROUND {n}', 'ROUND {n}'],
  'com.classifica':    ['Standings', 'Classifica'],
  'com.strategia':     ['Strategy',  'Strategia'],


  /* ================================================== titoli e descrizioni
     Le targhette che finiscono nella scheda dei motori di ricerca e nelle
     anteprime dei social. `og:locale` resta en_GB anche in italiano: dice cosa c'e'
     scritto NEL FILE, e nel file c'e' l'inglese — un crawler non esegue il nostro
     JavaScript, quindi una targhetta italiana su un file inglese sarebbe falsa.
     Le due lingue si annunciano con hreflang, allo stesso indirizzo piu' ?lang=it. */
  'meta.index.titolo':
    ['Muretto Box Virtuale — Formula 1 from the pit wall',
     'Muretto Box Virtuale — la Formula 1 vista dal muretto'],
  'meta.index.desc':
    ['Replay every race of the 2026 season lap by lap, decide for yourself when to pit, and look at the telemetry of any lap of any driver.',
     'Rivedi ogni gara della stagione 2026 giro per giro, decidi tu quando fermarsi ai box e guarda la telemetria di qualunque giro di qualunque pilota.'],
  'meta.stagione.titolo':
    ['2026 Season — Muretto Box Virtuale',
     'Stagione 2026 — Muretto Box Virtuale'],
  'meta.stagione.desc':
    ['The 2026 Formula 1 calendar: every race already run can be replayed lap by lap, with the strategy panel.',
     'Il calendario della Formula 1 2026: ogni gara corsa si rivede giro per giro, con il pannello strategia.'],
  'meta.telemetria.titolo':
    ['Telemetry — Muretto Box Virtuale',
     'Telemetria — Muretto Box Virtuale'],
  'meta.telemetria.desc':
    ['The telemetry of any lap of any driver: speed, throttle, brake and gears, and two laps side by side.',
     'La telemetria di qualunque giro di qualunque pilota: velocità, gas, freno e marce, e due giri a confronto.'],
  'meta.campionato.titolo':
    ['2026 Championship — Muretto Box Virtuale',
     'Campionato 2026 — Muretto Box Virtuale'],
  'meta.campionato.desc':
    ['Drivers\' and constructors\' standings of the 2026 Formula 1 season, with a card for every driver and every team.',
     'Classifica piloti e costruttori della Formula 1 2026, con la scheda di ogni pilota e di ogni squadra.'],
  'meta.analisi.titolo':
    ['Articles — Muretto Box Virtuale',
     'Articoli — Muretto Box Virtuale'],
  'meta.analisi.desc':
    ['One fact at a time, from the weekend data: telemetry, race pace, qualifying and strategy.',
     'Un fatto per volta, dai dati del weekend: telemetria, passo gara, qualifiche e strategia.'],
  'meta.forza.titolo':
    ['Car strength — Muretto Box Virtuale',
     'Forza-macchina — Muretto Box Virtuale'],
  'meta.forza.desc':
    ['How strong each car is in each 2026 race: an index of potential, not of finishing position. Pick the range of races and watch the order change.',
     'Quanto è forte ogni vettura in ogni gara del 2026: un indice del potenziale, non del piazzamento. Scegli l\'intervallo di gare e guarda come cambia la gerarchia.'],
  'meta.dati.titolo':
    ['Set-up and circuit DNA — Muretto Box Virtuale',
     'Assetto e DNA dei circuiti — Muretto Box Virtuale'],
  'meta.dati.desc':
    ['Where each team stands between top speed and cornering speed, and what character each circuit has between engine and downforce. 2026 season, race by race.',
     'Come è messa ogni squadra fra punta e curva, e che carattere ha ogni circuito fra motore e carico. Stagione 2026, gara per gara.'],
  'meta.whatif.titolo':
    ['What-If Simulator — Muretto Box Virtuale',
     'Simulatore What-If — Muretto Box Virtuale'],
  'meta.whatif.desc':
    ['Counterfactual strategy simulator: move the pit stop lap and compare two runs of the same engine, your strategy against the real one.',
     'Simulatore di strategie controfattuali: sposta il giro della sosta e confronta due run dello stesso motore, la tua strategia contro quella vera.'],
  'meta.live.titolo':
    ['Live — Muretto Box Virtuale',
     'Live — Muretto Box Virtuale'],
  'meta.live.desc':
    ['The race weekend as it happens: live timing and the next session.',
     'Il weekend di gara in diretta: classifica in tempo reale e la prossima sessione.'],
  'meta.gara.titolo':
    ['Race — Muretto Box Virtuale',
     'Gara — Muretto Box Virtuale'],
  'meta.gara.desc':
    ['Replay the race lap by lap and decide when to pit: the engine tells you where you come back out.',
     'Rivedi la gara giro per giro e decidi quando fermarsi ai box: il motore dice dove rientri.'],
  'meta.feedback.titolo':
    ['Report a problem — Muretto Box Virtuale',
     'Segnala un problema — Muretto Box Virtuale'],
  'meta.feedback.desc':
    ['Found something broken, a number that does not add up, or a page that makes no sense? Write to us here: we read every report by hand, one by one.',
     'Hai trovato qualcosa che non funziona, un numero che non torna o una pagina che non si capisce? Scrivicelo qui: le segnalazioni le leggiamo a mano, una per una.'],
  'meta.e404.titolo':
    ['Page not found — Muretto Box Virtuale',
     'Pagina non trovata — Muretto Box Virtuale'],

  /* ==================================================== index.html — la home */
  'index.hero_occhiello': ['Spa-Francorchamps · lap 20 of 44', 'Spa-Francorchamps · giro 20 di 44'],
  'index.hero_tit':       ['You decide<br><em>when to pit.</em>', 'Decidi tu<br><em>quando fermarsi.</em>'],
  'index.hero_sub':
    ['The <b>pit wall</b> decides the strategy. Here you decide it: you pit the leader and the engine says <b>where you come back out</b>, with the rivals at their real pace.',
     'Il <b>muretto box</b> decide la strategia. Qui la decidi tu: fermi il leader ai box e il motore dice <b>dove rientri</b>, coi rivali al loro passo reale.'],
  'index.hero_scelte':    ['When to pit', 'Quando fermarsi ai box'],
  'index.hero_gomma':     ['Which tyre you fit', 'Che gomma monti'],
  'index.hero_mesc_n':
    ['The compound <b>does not change</b> the answer: what changes it is <b>the moment</b>.',
     'La mescola <b>non cambia</b> la risposta: quello che la cambia è <b>il momento</b>.'],
  'index.hero_attesa':
    ['Choose when to pit: the engine says where you come back out, with the rivals at their real pace.',
     'Scegli quando fermarti: il motore dice dove rientri, coi rivali al loro passo reale.'],
  'index.cta_gara':       ['Try it on the real race', 'Prova sulla gara vera'],
  'index.hero_torre':     ['Simulated standings', 'Classifica simulata'],
  'index.rivedi':         ['Replay', 'Rivedi'],
  'index.firma':          ["<span>It's you,</span> <span><em>on the pit wall.</em></span>",
                           '<span>Sei tu,</span> <span><em>al muretto.</em></span>'],

  'index.cosa_trovi':     ['What you will find', 'Cosa trovi'],
  'index.porta1_t':       ['The races', 'Le gare'],
  'index.porta1_p':
    ['Every Grand Prix can be replayed from start to finish: the cars on track, the order changing, the safety cars. And the strategy panel always open.',
     "Ogni Gran Premio si rivede dall'inizio alla fine: le auto in pista, la classifica che cambia, le safety car. E il pannello strategia sempre aperto."],
  'index.porta1_go':      ['Go to the season', 'Vai alla stagione'],
  'index.porta2_t':       ['The telemetry', 'La telemetria'],
  'index.porta2_p':
    ['Pick the driver and <b>pick the lap</b>: speed, throttle, brake and gears of that exact lap. Two laps side by side, where time is gained and where it is lost.',
     'Scegli il pilota e <b>scegli il giro</b>: velocità, gas, freno e marce di quel giro preciso. Due giri a confronto, dove si guadagna e dove si perde.'],
  'index.porta2_go':      ['Open the telemetry', 'Apri la telemetria'],
  'index.porta3_t':       ['The championship', 'Il campionato'],
  'index.porta3_p':
    ['Drivers and constructors, race after race. With a card for every driver: the season under way and the career.',
     'Piloti e costruttori, gara dopo gara. Con la scheda di ogni pilota: la stagione in corso e la carriera.'],
  'index.porta3_go':      ['See the standings', 'Vedi le classifiche'],

  'index.ultima_gara':    ['The last race', "L'ultima gara"],
  'index.tutti':          ['all of them', 'tutti'],
  'index.nessuna_gara':   ['No race published yet.', 'Nessuna gara ancora pubblicata.'],
  'index.vince':          ['wins', 'vince'],
  'index.rivedi_gara':    ['Replay the race', 'Rivedi la gara'],

  'index.ric_tit':        ['If something is wrong, <em style="font-style:normal;color:var(--rosso)">say so</em>',
                           'Se qualcosa non va, <em style="font-style:normal;color:var(--rosso)">dillo</em>'],
  'index.ric_p':
    ['So far only we have looked at this site, and whoever builds a thing stops seeing it. If you find a number that does not add up, a chart that stays empty or a page that makes no sense, write to us: we read the reports by hand, and the ones that describe a real defect become a fix.',
     "Questo sito finora l'abbiamo guardato solo noi, e chi costruisce una cosa smette di vederla. Se trovi un numero che non torna, un grafico che resta vuoto o una pagina che non si capisce, scrivicelo: le segnalazioni le leggiamo a mano, e quelle che descrivono un difetto vero diventano una correzione."],

  /* ==================================================== hero.mjs — la home giocata */
  'hero.giro':          ['LAP',  'GIRO'],
  'hero.giri_sigla':    ['LAPS', 'GIRI'],
  'hero.sosta_corso':   ['Pit stop<br>under way', 'Sosta<br>in corso'],
  'hero.neutralizzato': ['neutralised',  'neutralizzato'],
  'hero.bandiera_verde':['green flag',   'bandiera verde'],
  'hero.aria_scelta':   ['pit stop on lap {giro}, {bandiera}. You come back out in position {pos}.',
                         'sosta al giro {giro}, {bandiera}. Rientri in posizione {pos}.'],
  'hero.rientri':       ['you come out', 'rientri'],
  'hero.et_ora':        ['PIT NOW', 'BOX ORA'],
  'hero.et_dopo_1':     ['WAIT {n} LAP',  'ASPETTA {n} GIRO'],
  'hero.et_dopo_n':     ['WAIT {n} LAPS', 'ASPETTA {n} GIRI'],
  'hero.gomma_su':      ['tyre fitted right now.', 'gomma montata adesso.'],
  'hero.durata_max':
    ['Longest this compound lasts today: {n} laps — the compound does not change the answer (in 2026 it does not separate degradation)',
     'Durata massima di questa mescola oggi: {n} giri — la mescola non cambia la risposta (nel 2026 non separa il degrado)'],
  'hero.fonte_pitloss': ['Pit-loss <b>{s} s</b>.', 'Pit-loss <b>{s} s</b>.'],
  'hero.fonte_degrado': ['Degradation <b>{rho} s/lap</b> for every lap of tyre life.',
                         'Degrado <b>{rho} s/giro</b> per ogni giro di gomma.'],
  'hero.resti_comando': ['You stay in the lead', 'Resti al comando'],
  'hero.mantieni':      ['You keep your position', 'Mantieni la posizione'],
  'hero.guadagni_1':    ['You gain {n} position',  'Guadagni {n} posizione'],
  'hero.guadagni_n':    ['You gain {n} positions', 'Guadagni {n} posizioni'],
  'hero.perdi_1':       ['You lose {n} position',  'Perdi {n} posizione'],
  'hero.perdi_n':       ['You lose {n} positions', 'Perdi {n} posizioni'],
  'hero.gap_non_quant': ['gap not quantifiable &middot; {n} rivals pitting with you',
                         'gap non quantificabile &middot; {n} rivali in sosta con te'],
  'hero.dietro_di':     ['behind <b>{chi}</b> by {s} s', 'dietro <b>{chi}</b> di {s} s'],
  'hero.in_testa':      ['leading the race', 'in testa alla corsa'],
  'hero.altra_strada':  ['other road', 'altra strada'],

  /* ============================================== stagione.html — il calendario */
  'stagione.occhiello':   ['Formula 1 · Calendar', 'Formula 1 · Calendario'],
  'stagione.titolo':      ['2026 <em>Season</em>', 'Stagione <em>2026</em>'],
  'stagione.sottotitolo':
    ['Every Grand Prix already run can be replayed from start to finish, with the strategy in your hands. Tap a race to open it.',
     "Ogni Gran Premio già corso si rivede dall'inizio alla fine, con la strategia in mano. Tocca una gara per aprirla."],
  'stagione.gare_corse':  ['Races run', 'Gare corse'],
  'stagione.resto':       ['The rest of the calendar', 'Il resto del calendario'],
  'stagione.prossima':    ['next up', 'prossima'],
  'stagione.da_correre':  ['still to run', 'da correre'],
  'stagione.da_rivedere': ['races to replay', 'gare da rivedere'],
  'stagione.nel_calendario': ['in the calendar', 'nel calendario'],
  'stagione.giri_disp':   ['laps available', 'giri disponibili'],
  'stagione.n_di_n':      ['{a} of {b}', '{a} di {b}'],

  /* =========================================== campionato.html — le classifiche */
  'camp.titolo':        ['The <em>standings</em>', 'La <em>classifica</em>'],
  'camp.occhiello':     ['Championship 2026 · after the {gara}', 'Campionato 2026 · dopo il {gara}'],
  'camp.via':           ['start', 'via'],
  'camp.piloti':        ['Drivers', 'Piloti'],
  'camp.costruttori':   ['Constructors', 'Costruttori'],
  'camp.costruttore':   ['Constructor', 'Costruttore'],
  'camp.pos':           ['Pos', 'Pos'],
  'camp.vittorie':      ['Wins', 'Vittorie'],
  'camp.punti':         ['Points', 'Punti'],
  'camp.leader':        ['LEADER', 'LEADER'],
  'camp.motore':        ['{m} engine', 'motore {m}'],
  'camp.scheda_pilota': ['Driver card', 'Scheda del pilota'],
  'camp.scheda_squadra':['Team card', 'Scheda della squadra'],
  'camp.chiudi':        ['Close', 'Chiudi'],
  'camp.stagione_2026': ['2026 season', 'Stagione 2026'],
  'camp.in_carriera':   ['Career', 'In carriera'],
  'camp.c_posizione':   ['position', 'posizione'],
  'camp.c_punti':       ['points', 'punti'],
  'camp.c_vittorie':    ['wins', 'vittorie'],
  'camp.c_podi':        ['podiums', 'podi'],
  'camp.c_pole':        ['poles', 'pole'],
  'camp.c_titoli':      ['titles', 'titoli'],
  'camp.c_gran_premi':  ['grands prix', 'gran premi'],
  'camp.c_media_griglia':['avg. grid', 'media griglia'],
  'camp.c_media_arrivo':['avg. finish', 'media arrivo'],
  'camp.ultima_vittoria':['Last win: {data}.', 'Ultima vittoria: {data}.'],

  /* ================================================ analisi.html — gli articoli */
  'analisi.occhiello':    ['Analysis · articles', 'Analisi · articoli'],
  'analisi.titolo':       ['One fact <em>at a time</em>', 'Un fatto <em>per volta</em>'],
  'analisi.sottotitolo':
    ['Short pieces that start from one number of the weekend and arrive at a single conclusion. No driver ratings, no transfer rumours.',
     'Pezzi brevi che partono da un numero del weekend e arrivano a una conclusione sola. Niente pagelle, niente voci di mercato.'],
  'analisi.tag_ogni_gara':     ['Interactive · updates after every race', 'Interattivo · si aggiorna a ogni gara'],
  'analisi.tag_controfattuale':['Interactive · counterfactual simulation', 'Interattivo · simulazione controfattuale'],
  'analisi.strum_forza_t': ['Car strength, race by race', 'Forza-macchina, gara per gara'],
  'analisi.strum_forza_d':
    ['How strong each car is in each race — from potential, not from finishing position. The slider picks the range and shows how the order changes.',
     "Quanto è forte ogni vettura in ogni gara — dal potenziale, non dal piazzamento. Il cursore sceglie l'intervallo e mostra come cambia la gerarchia."],
  'analisi.strum_dati_t':  ['Set-up and circuit DNA', 'Assetto e DNA dei circuiti'],
  'analisi.strum_dati_d':
    ['Where each team has chosen to be slow, between top speed and cornering; and what character each track has, between engine and downforce.',
     'Dove ogni squadra ha scelto di essere lenta, fra punta e curva; e che carattere ha ogni tracciato, fra motore e carico.'],
  'analisi.strum_whatif_t':['What-If &amp; Strategy Simulator', 'Simulatore What-If &amp; Strategie'],
  'analisi.strum_whatif_d':
    ['Move the pit stop lap and watch what changes: your strategy and the real one, run through the same engine. It is a game, not a prediction.',
     'Sposta il giro della sosta e guarda che cosa cambia: la tua strategia e quella vera, girate nello stesso motore. È un gioco, non una previsione.'],
  'analisi.apri':         ['Open', 'Apri'],
  'analisi.simula':       ['Simulate', 'Simula'],
  'analisi.team_tema':    ['Team &amp; Topic', 'Team &amp; Tema'],
  'analisi.tutte_gare':   ['All races', 'Tutte le gare'],
  'analisi.tutti_temi':   ['All topics', 'Tutti i temi'],
  'analisi.n_visti':      ['{n} articles shown', '{n} articoli visualizzati'],

  /* ============================================== i nomi dei Gran Premi
     La chiave e' il nome ITALIANO perche' e' quello che l'artefatto porta scritto —
     il ragionamento per esteso sta in muro.mjs::gpNome. `gp.` e' il nome corto (le
     schede del calendario, le pillole dei filtri), `gpt.` il titolo lungo. */
  'gp.Australia':         ['Australia', 'Australia'],
  'gp.Cina':              ['China', 'Cina'],
  'gp.Giappone':          ['Japan', 'Giappone'],
  'gp.Miami':             ['Miami', 'Miami'],
  'gp.Canada':            ['Canada', 'Canada'],
  'gp.Monaco':            ['Monaco', 'Monaco'],
  'gp.Spagna':            ['Spain', 'Spagna'],
  'gp.Austria':           ['Austria', 'Austria'],
  'gp.Gran Bretagna':     ['Great Britain', 'Gran Bretagna'],
  'gp.Belgio':            ['Belgium', 'Belgio'],
  'gp.Ungheria':          ['Hungary', 'Ungheria'],
  'gp.Olanda':            ['Netherlands', 'Olanda'],
  'gp.Italia':            ['Italy', 'Italia'],
  'gp.Madrid':            ['Madrid', 'Madrid'],
  'gp.Azerbaigian':       ['Azerbaijan', 'Azerbaigian'],
  'gp.Singapore':         ['Singapore', 'Singapore'],
  'gp.Stati Uniti':       ['United States', 'Stati Uniti'],
  'gp.Messico':           ['Mexico', 'Messico'],
  'gp.San Paolo':         ['São Paulo', 'San Paolo'],
  'gp.Las Vegas':         ['Las Vegas', 'Las Vegas'],
  'gp.Qatar':             ['Qatar', 'Qatar'],
  'gp.Abu Dhabi':         ['Abu Dhabi', 'Abu Dhabi'],
  'gpt.Australia':        ['Australian GP', "GP d'Australia"],
  'gpt.Cina':             ['Chinese GP', "GP di Cina"],
  'gpt.Giappone':         ['Japanese GP', "GP del Giappone"],
  'gpt.Miami':            ['Miami GP', "GP di Miami"],
  'gpt.Canada':           ['Canadian GP', "GP del Canada"],
  'gpt.Monaco':           ['Monaco GP', "GP di Monaco"],
  'gpt.Spagna':           ['Spanish GP — Barcelona', "GP di Spagna — Barcellona"],
  'gpt.Austria':          ['Austrian GP', "GP d'Austria"],
  'gpt.Gran Bretagna':    ['British GP', "GP di Gran Bretagna"],
  'gpt.Belgio':           ['Belgian GP', "GP del Belgio"],
  'gpt.Ungheria':         ['Hungarian GP', "GP d'Ungheria"],
  'gpt.Olanda':           ['Dutch GP', "GP d'Olanda"],
  'gpt.Italia':           ['Italian GP', "GP d'Italia"],
  'gpt.Madrid':           ['Madrid GP', "GP di Madrid"],
  'gpt.Azerbaigian':      ['Azerbaijan GP', "GP dell'Azerbaigian"],
  'gpt.Singapore':        ['Singapore GP', "GP di Singapore"],
  'gpt.Stati Uniti':      ['United States GP', "GP degli Stati Uniti"],
  'gpt.Messico':          ['Mexican GP', "GP del Messico"],
  'gpt.San Paolo':        ['São Paulo GP', "GP di San Paolo"],
  'gpt.Las Vegas':        ['Las Vegas GP', "GP di Las Vegas"],
  'gpt.Qatar':            ['Qatar GP', "GP del Qatar"],
  'gpt.Abu Dhabi':        ['Abu Dhabi GP', "GP di Abu Dhabi"],

  /* ============================================== telemetria.html + le sessioni */
  // Le SIGLE delle sessioni (fp1, sprint_quali) vengono dai fogli FIA e non si traducono:
  // qui si traduce solo il nome per esteso.
  'sess.fp1':           ['Practice 1', 'Libere 1'],
  'sess.fp2':           ['Practice 2', 'Libere 2'],
  'sess.fp3':           ['Practice 3', 'Libere 3'],
  'sess.sprint_quali':  ['Sprint Quali', 'Quali sprint'],
  'sess.sprint':        ['Sprint', 'Sprint'],
  'sess.qualifiche':    ['Qualifying', 'Qualifiche'],
  'sess.gara':          ['Race', 'Gara'],

  'tele.occhiello':     ['Telemetry · 2026 season', 'Telemetria · stagione 2026'],
  'tele.titolo':        ['Pick the <em>lap</em>', 'Scegli il <em>giro</em>'],
  'tele.sottotitolo':
    ['Every timed lap of every driver, in every session of the weekend. Take two and see where the time is gained.',
     'Ogni giro cronometrato di ogni pilota, in ogni sessione del weekend. Prendine due e vedi dove si guadagna.'],
  'tele.aria_gp':       ['Grand Prix', 'Gran Premio'],
  'tele.aria_sess':     ['Session', 'Sessione'],
  'tele.confronta':     ['Compare with…', 'Confronta con…'],
  'tele.annulla':       ['Cancel', 'Annulla'],
  'tele.tocca_secondo': ['Tap the second driver.', 'Tocca il secondo pilota.'],
  'tele.sul_tracciato': ['On the track', 'Sul tracciato'],
  'tele.giri_confronto':['Laps compared', 'Giri a confronto'],
  'tele.il_giro':       ['The lap', 'Il giro'],
  'tele.scegli_pilota': ['Pick a driver to see their laps.', 'Scegli un pilota per vedere i suoi giri.'],
  'tele.carico':        ['Loading the session…', 'Carico la sessione…'],
  'tele.sessione_assente': ['This session is not available.', 'Questa sessione non è disponibile.'],
  'tele.cap_piloti':    ['{n} drivers · best lap', '{n} piloti · miglior giro'],
  'tele.senza_tele':    ['no telemetry', 'senza telemetria'],
  'tele.senza_tele_title': ['no lap with recorded telemetry', 'nessun giro con telemetria registrata'],
  'tele.nessun_giro_tele':
    ['{sig} has no lap with recorded telemetry in this session.',
     '{sig} non ha nessun giro con la telemetria registrata in questa sessione.'],
  'tele.giro_senza_tele': ['Lap {giro} of {sig} has no recorded telemetry.',
                           'Il giro {giro} di {sig} non ha la telemetria registrata.'],
  'tele.in_lap':        ['in-lap', 'giro di rientro ai box'],
  'tele.out_lap':       ['out-lap', 'giro di uscita dai box'],
  'tele.suoi_giri':     ['their laps — tap to change', 'i suoi giri — tocca per cambiare'],
  'tele.a_confronto':   ['compared — tap to change', 'a confronto — tocca per cambiare'],
  'tele.velocita':      ['Speed', 'Velocità'],
  'tele.acceleratore':  ['Throttle', 'Acceleratore'],
  'tele.freno':         ['Brake', 'Freno'],
  'tele.freno_sigla':   ['BRAKE', 'FRENO'],
  'tele.marcia':        ['Gear', 'Marcia'],
  'tele.distacco':      ['Gap', 'Distacco'],
  'tele.distacco_pan':  ['Gap · {a} against {b}', 'Distacco · {a} rispetto a {b}'],
  'tele.giro_box':
    ['Lap {giro} goes through the pits: it does not cover the track lap, so it is not coloured on the map.',
     'Il giro {giro} passa dai box: non copre il giro di pista, quindi non si colora sul tracciato.'],
  'tele.pista_assente': ['Track map not available for this GP.', 'Tracciato non disponibile per questo GP.'],
  'tele.nota_box':
    ['One of the two laps goes through the pits: it is not a whole track lap, so the gap cannot be computed.',
     'Uno dei due giri passa dai box: non è un giro di pista intero, quindi il distacco non si calcola.'],
  'tele.nota_cambia_b':
    ['To change the second driver: «Compare with…» on the left, or ⇧+click on their name.',
     'Per cambiare il secondo pilota: «Confronta con…» a sinistra, o ⇧+clic sul suo nome.'],
  'tele.nota_confronta':
    ['Press «Compare with…» on the left to put two laps side by side.',
     'Premi «Confronta con…» a sinistra per mettere due giri a confronto.'],
  'tele.togli_confronto': ['Remove the comparison', 'Togli il confronto'],
  'tele.cf_giro':       ['lap', 'giro'],
  'tele.cf_punta':      ['top speed', 'punta'],
  'tele.cf_gas_pieno':  ['full throttle (time)', 'gas pieno (tempo)'],
  'tele.cf_gomma':      ['tyre', 'gomma'],

  /* ================================================== 404.html — la pagina persa */
  'e404.occhiello':   ['Error 404', 'Errore 404'],
  'e404.titolo':      ['This page <em>does not exist</em>', 'Questa pagina <em>non esiste</em>'],
  'e404.sottotitolo':
    ['The address you followed leads nowhere: maybe an old link, maybe a typo. You can start again from here.',
     "L'indirizzo che hai seguito non porta a nulla: forse un vecchio link, forse un refuso. Da qui si riparte."],
  'e404.le_gare':     ['The races', 'Le gare'],
  'e404.home':        ['Home', 'Home'],

  /* ================================== dati.html — assetto e DNA dei circuiti */
  'strum.occhiello':    ['Analysis · season tool', 'Analisi · strumento di stagione'],
  'dati.titolo':        ['Set-up and circuit <em>DNA</em>', 'Assetto e <em>DNA</em> dei circuiti'],
  'dati.sottotitolo':
    ['Two questions answered by the same data. Where a team stands between top speed and cornering speed — that is, where it has chosen to be slow. And what character a track has between engine and downforce: how much of the lap is spent at full throttle.',
     'Due domande che si rispondono con lo stesso dato. Come è messa una squadra fra velocità di punta e velocità in curva — cioè dove ha scelto di essere lenta. E che carattere ha un tracciato fra motore e carico: quanta parte del giro si passa a tutto gas.'],
  'dati.vista':         ['View', 'Vista'],
  'dati.stagione':      ['Season', 'Stagione'],
  'dati.ultime5':       ['Last 5', 'Ultime 5'],
  'dati.ultime5_lungo': ['last 5 races', 'ultime 5 gare'],
  'dati.stagione_n':    ['season, {n} races', 'stagione, {n} gare'],
  'dati.per_gara':      ['By race…', 'Per gara…'],
  'dati.aria_gara':     ['Choose a race', 'Scegli una gara'],
  'dati.cap_ass':       ['Set-up · top speed against cornering', 'Assetto · punta contro curva'],
  'dati.sub_ass':
    ['Each dot is a team: to the right the ones quick on the straight, at the top the ones quick in the corners. The diagonal is not a verdict — it is the compromise, and everyone resolves it their own way.',
     'Ogni pallino è una squadra: a destra chi va forte sul dritto, in alto chi va forte in curva. La diagonale non è un giudizio — è il compromesso, e ognuno lo scioglie a modo suo.'],
  'dati.cap_dna':       ['Circuit DNA · engine against downforce', 'DNA dei circuiti · motore contro carico'],
  'dati.sub_dna':
    ['The share of the lap at full throttle is the cleanest signature of a track: the higher it is, the more the engine counts; the lower it is, the more aerodynamic downforce counts.',
     'La percentuale di giro a tutto gas è la firma più pulita di un tracciato: più è alta, più conta il motore; più è bassa, più conta il carico aerodinamico.'],
  'dati.aria_ass':      ['Top speed against cornering speed, by team',
                         'Velocità di punta contro velocità in curva, per squadra'],
  'dati.aria_dna':      ['Share of the lap at full throttle, by circuit',
                         'Percentuale di giro a tutto gas, per circuito'],
  'dati.asse_x':        ['TOP SPEED (km/h) →', 'VELOCITÀ DI PUNTA (km/h) →'],
  'dati.asse_y':        ['↑ IN CORNERS (km/h)', '↑ IN CURVA (km/h)'],
  'dati.th_punta':      ['Top km/h', 'Punta km/h'],
  'dati.th_curva':      ['Corners km/h', 'In curva km/h'],
  'dati.th_circuito':   ['Circuit', 'Circuito'],
  'dati.th_gas':        ['Full throttle %', 'Tutto gas %'],
  'dati.th_curve':      ['Corners', 'Curve'],
  'dati.th_lente':      ['Slow', 'Lente'],
  'dati.th_veloci':     ['Fast', 'Veloci'],
  'dati.th_media_curva':['Corner avg.', 'Media curva'],
  'dati.nel_conto_1':   ['{n} race counted', '{n} gara nel conto'],
  'dati.nel_conto_n':   ['{n} races counted', '{n} gare nel conto'],
  'dati.nota_fondo':    ['{n} races in the dashboard, latest {ultima}.',
                         '{n} gare nel cruscotto, ultima {ultima}.'],

  /* ================================================ forza.html — forza-macchina */
  'forza.titolo':       ['Car <em>strength</em>', 'Forza-<em>macchina</em>'],
  'forza.sottotitolo':
    ["Finishing position lies: whoever starts at the back after a penalty races stuck in traffic, and their pace never shows. This is an index of the car's <b>potential</b> — one-lap and race pace, normalised race by race. Pick the range and watch the order change.",
     "Il piazzamento mente: chi parte indietro per una penalità corre imbottigliato, e il suo passo non si vede. Questo è un indice del <b>potenziale</b> della vettura — giro secco e passo gara, normalizzati gara per gara. Scegli l'intervallo e guarda come cambia la gerarchia."],
  'forza.intervallo':   ['Race range', 'Intervallo gare'],
  'forza.aria_min':     ['First race of the range', "Prima gara dell'intervallo"],
  'forza.aria_max':     ['Last race of the range', "Ultima gara dell'intervallo"],
  'forza.traccia':      ['Trace', 'Traccia'],
  'forza.m_indice':     ['Index', 'Indice'],
  'forza.m_giro_secco': ['One lap', 'Giro secco'],
  'forza.m_passo':      ['Pace', 'Passo'],
  'forza.n_indice':         ['strength index', 'indice di forza'],
  'forza.n_potenziale_pct': ['one-lap potential', 'potenziale sul giro secco'],
  'forza.n_passo_pct':      ['race pace', 'passo gara'],
  'forza.evoluzione':   ['Evolution', 'Evoluzione'],
  'forza.classifica_int':['Standings for the range', "Classifica dell'intervallo"],
  'forza.th_media':     ['Average', 'Media'],
  'forza.th_tendenza':  ['Trend', 'Tendenza'],
  'forza.isola':        ['Isolate this team in the chart', 'Isola questa squadra nel grafico'],
  'forza.solo':         ['{chi} only — tap again for all', 'solo {chi} — tocca di nuovo per tutte'],
  'forza.0_100':        ['0–100 per race', '0–100 per gara'],
  'forza.media_di_1':   ['average of {n} race',  'media di {n} gara'],
  'forza.media_di_n':   ['average of {n} races', 'media di {n} gare'],
  'com.gare_n':         ['{n} races', '{n} gare'],
  'forza.aria_graf':    ['Evolution of {m} by team', "Evoluzione dell'{m} per squadra"],
  'forza.tutte':        ['Back to all of them', 'Torna a vederle tutte'],
  'forza.isola_chi':    ['Isolate {chi}', 'Isola {chi}'],
  'forza.riordina':     ['Reorder', 'Riordina'],

  /* ================================================== live.html — la diretta */
  'live.collego':       ['connecting…', 'collego…'],
  'live.riconnetto':    ['reconnecting…', 'riconnetto…'],
  'live.in_diretta':    ['live', 'in diretta'],
  'live.nessuna_sessione': ['no session', 'nessuna sessione'],
  'live.classifica_rt': ['Live timing', 'Classifica in tempo reale'],
  'live.calendario':    ['Calendar', 'Calendario'],
  'live.stagione_finita': ['Season over', 'Stagione finita'],
  'live.calendario_completo': ['The 2026 calendar is complete: we start again next year.',
                               'Il calendario 2026 è completo: si riparte il prossimo anno.'],
  'live.prossimo':      ['next up', 'prossimo appuntamento'],
  'live.prima':         ['first', 'prima'],
  'live.giorni':        ['days', 'giorni'],
  'live.ore':           ['hours', 'ore'],
  'live.minuti':        ['minutes', 'minuti'],
  'live.secondi':       ['seconds', 'secondi'],
  'live.il_muretto':    ['The pit wall', 'Il muretto'],
  'live.tocca_pilota':  ['Tap a driver in the standings, pick the tyre and press PIT NOW.',
                         'Tocca un pilota nella classifica, scegli la gomma e premi BOX ORA.'],
  'live.scegli_prima':  ['Pick a driver in the standings first', 'Scegli prima un pilota nella classifica'],
  'live.onesta':
    ['It is a <b>projection</b>: the future has not happened yet, so <b>the rivals do not react</b> and beyond ~6 laps it is not validated.',
     'È una <b>proiezione</b>: il futuro non è ancora successo, quindi <b>i rivali non reagiscono</b> e oltre ~6 giri non è validata.'],
  'live.non_e_gara':
    ['No race is being run here: without a distance to cover there is no pit stop to judge. The pit wall comes back for the race.',
     "Qui non si corre una gara: senza una distanza da coprire non c'è una sosta da giudicare. Il muretto torna in gara."],
  'live.giro_incompleto': ['The current lap is not complete yet: try again shortly.',
                           'Il giro in corso non è ancora completo: riprova fra poco.'],
  'live.motore_assente': ['The engine is not available on this page.', 'Il motore non è disponibile in questa pagina.'],
  'live.non_attivo':    ['{chi} is no longer running (retired or not classified on lap {giro}).',
                         '{chi} non è più attivo in pista (ritirato o non classificato al giro {giro}).'],
  'live.sta_imparando':
    ['The pit wall is still learning the race: {motivo}. If you joined after the start, a few clean laps are needed.',
     'Il muretto sta ancora imparando la gara: {motivo}. Se ti sei collegato a corsa iniziata, servono pochi giri puliti.'],
  'live.due_soste_no':  ['⚠️ Mandatory second stop not achievable', '⚠️ Seconda sosta obbligatoria non realizzabile'],
  'live.due_soste_no_p':
    ['Fitting {m1} again, you would be forced into another stop before the flag by the rules (two different compounds required). Only {n} laps remain: pick another tyre ({m2}) to finish the race on one stop.',
     "Rimontando {m1}, dovresti fare per forza un'altra sosta prima della bandiera per regolamento (obbligo 2 mescole diverse). Mancano solo {n} giri: scegli un'altra gomma ({m2}) per completare la gara a 1 sosta."],
  'live.senza_tempo':   ['{chi} has no recorded time on lap {giro} (retired or lapped).',
                         '{chi} non ha un tempo registrato al giro {giro} (ritirato o doppiato).'],
  'live.motore_rifiuta':['The engine refuses this stop: {motivo}', 'Il motore rifiuta questa sosta: {motivo}'],
  'live.piano_non_valido': ['Invalid plan: try another tyre.', "Piano non valido: prova un'altra gomma."],
  'live.se_monta':      ['if {chi} fits {m} on lap {giro}', 'se {chi} monta {m} al giro {giro}'],
  'live.se_si_ferma':   ['if {chi} pits on lap {giro}', 'se {chi} si ferma al giro {giro}'],
  'live.bandiera_2':    ['at the flag on a 2-stop strategy ({m1} ➔ {m2}).',
                         'alla bandiera con strategia a 2 soste ({m1} ➔ {m2}).'],
  'live.bandiera_1':    ['at the flag on {m} tyres (one stop to the end).',
                         'alla bandiera con gomma {m} (1 sosta fino alla fine).'],
  'live.nota_reg':      ['⚠️ Rules note (mandatory 2nd stop): ', '⚠️ Nota Regolamento (2ª sosta obbligatoria): '],
  'live.nota_reg_p':
    ['Fitting {m1} again, you will be forced into another stop before the flag to meet the two-compound rule: the engine has projected the 2nd stop on lap {giro} for {m2} tyres.',
     "Rimontando gomma {m1}, dovrai fare per forza un'altra sosta prima della bandiera per rispettare l'obbligo di due mescole diverse: il motore ha proiettato la 2ª sosta al giro {giro} per gomma {m2}."],
  'live.pannello_strategia': ['The strategy panel', 'Il pannello strategia'],
  'live.nel_frattempo': ['In the meantime', 'Nel frattempo'],
  'live.pannello_p':
    ['During the race the same pit wall question — «if I pit now, where do I come back out?» — is asked on the race page, on the data just recorded.',
     'Durante la gara la stessa domanda del muretto — «se mi fermo ora, dove rientro?» — si fa sulla pagina della gara, sui dati appena registrati.'],
  'live.frattempo_p':
    ['There is no session under way. You can replay the last race and try the strategy: it is the same panel you will see here live.',
     "Non c'è una sessione in corso. Puoi rigiocare l'ultima gara e provare la strategia: è lo stesso pannello che vedrai qui in diretta."],
  'live.rivedi_gara':   ['Replay {gp}', 'Rivedi {gp}'],
  'live.aria_scegli':   ['Pick {chi} for the pit wall', 'Scegli {chi} per il muretto'],
  'live.occhiello':     ['Live', 'Diretta'],
  'live.titolo':        ['The pit wall <em>live</em>', 'Il muretto <em>in diretta</em>'],

  /* ============================ il motore: parole comuni a whatif e pagina-gara */
  // Il VERDETTO del Simulation Director e le ASSUNZIONI dichiarate arrivano dal kernel
  // (simulatore/scenario/costruttore.mjs), che e' congelato e le produce come dato, in
  // italiano, con dentro i numeri della gara. Qui si traduce la cornice — l'esito, i
  // titoli, l'avviso — e non il testo del kernel: vedi `sim.avviso_kernel`.
  'sim.respinge':       ['the Simulation Director REJECTS this run:',
                         'il Simulation Director RESPINGE questo run:'],
  'sim.approvato':      ['Simulation Director: approved', 'Simulation Director: approvato'],
  'sim.sospetti':       ['{n} suspect items (non-blocking)', '{n} sospetti (non bloccanti)'],
  'sim.congelamento':   ['freeze on lap {giro}', 'congelamento al giro {giro}'],
  'sim.gara_reale':     ['real race', 'gara reale'],
  'sim.dal_lapchart':   ['from the lap chart, without post-race penalties',
                         'dal lap chart, senza penalità post-gara'],
  'sim.strategia_vera': ['real strategy · in the engine', 'strategia vera · nel motore'],
  'sim.metro_giusto':   ['same engine, same assumptions: this is the right yardstick',
                         'stesso motore, stesse assunzioni: è il metro giusto'],
  'sim.non_simulabile': ['not simulable (non-slick tyres or unreadable stops) — declared',
                         'non simulabile (gomme non-slick o soste illeggibili) — dichiarato'],
  'sim.non_verificato': ['NOT VERIFIED', 'NON VERIFICATO'],
  'sim.orizzonte':
    ['<b>HORIZON</b> — projection out to lap {giro}: tens of laps against the ~6 validated ones of the answer. <small>measured: over the whole race the engine and «change nothing» are indistinguishable</small>',
     '<b>ORIZZONTE</b> — proiezione fino al giro {giro}: decine di giri contro i ~6 validati della risposta. <small>misurato: sulla gara intera il motore e «non cambia niente» sono indistinguibili</small>'],
  'sim.avviso_kernel':
    ['The assumptions below are written in Italian by the simulation kernel, which produces them as data together with the numbers of this race.',
     'Le assunzioni qui sotto le scrive il kernel della simulazione, insieme ai numeri di questa gara.'],

  /* ================================================ whatif.html + whatif.mjs */
  'wif.occhiello':      ['Strategy · Counterfactual scenarios', 'Strategia · Scenari Controfattuali'],
  'wif.titolo':         ['<em>What-If</em> simulator', 'Simulatore <em>What-If</em>'],
  'wif.sottotitolo':
    ["Move the pit stop lap and watch what changes. The two answers come out of the <b>same engine</b>: your strategy and the real one, both run as a simulation. It is the only comparison that isolates the choice instead of measuring the model's error.",
     "Sposta il giro della sosta e guarda che cosa cambia. Le due risposte escono dallo <b>stesso motore</b>: la tua strategia e quella vera, girate entrambe come simulazione. È l'unico confronto che isola la scelta invece di misurare l'errore del modello."],
  'wif.giro_alt':       ['Alternative pit lap', 'Giro Sosta Alternativo'],
  'wif.mescola_montata':['Compound fitted', 'Mescola Montata'],
  'wif.caricamento_par':['Loading parameters…', 'Caricamento parametri…'],
  'wif.caricamento':    ['Loading…', 'Caricamento…'],
  'wif.sosta_reale':    ['Real stop', 'Sosta reale'],
  'wif.sosta_wif':      ['What-If stop', 'Sosta What-If'],
  'wif.pos_rientro':    ['Position on rejoining', 'Posizione al rientro'],
  'wif.sub_rientro':    ['in the What-If run, against the rivals of that same run',
                         'nel run What-If, contro i rivali dello stesso run'],
  'wif.delta_bandiera': ['Delta at the flag', 'Delta alla bandiera'],
  'wif.sub_delta':      ['What-If minus the real strategy, same engine',
                         'What-If meno strategia vera, stesso motore'],
  'wif.nota_metodo':
    ['This page is a game, not a prediction. Over the whole race the engine and «change nothing» are indistinguishable: the value is in the comparison between two runs, not in the absolute number.',
     'Questa pagina è un gioco, non una previsione. Sulla gara intera il motore e «non cambia niente» sono indistinguibili: il valore sta nel confronto fra due run, non nel numero assoluto.'],
  'wif.no_lapchart':    ['no race with a lap chart in the manifest', 'nessuna gara con lap chart nel manifest'],
  'wif.non_parte':      ['the page does not start: {motivo}', 'la pagina non parte: {motivo}'],
  'wif.preparo':        ['preparing the race in the engine…', 'preparo la gara nel motore…'],
  'wif.non_simulabile': ['{gp} is not simulable: {motivo}', '{gp} non è simulabile: {motivo}'],
  'wif.g_sigla':        ['l.', 'g.'],
  'wif.soste_1':        ['{n} stop ({lista})', '{n} sosta ({lista})'],
  'wif.soste_n':        ['{n} stops ({lista})', '{n} soste ({lista})'],
  'wif.nessuna_sosta':  ['— none', '— nessuna'],
  'wif.ritirato':       [' — they retired', ' — si è ritirato'],
  'wif.non_partito':    [' — they did not start', ' — non è partito'],
  'wif.mai_fermato':    ['{chi} never pitted in this race{perche}: there is no stop to move',
                         "{chi} non si è mai fermato in questa gara{perche}: non c'è una sosta da spostare"],
  'wif.rigioca':        ['the engine is replaying the race…', 'il motore sta rigiocando la gara…'],
  'wif.niente_da_simulare': ['nothing to simulate: {motivo}', 'niente da simulare: {motivo}'],
  'wif.motore_rifiuta': ['the engine refuses this scenario: {motivo}',
                         'il motore rifiuta questo scenario: {motivo}'],
  'wif.con_la_tua':     ['with your stop', 'con la tua sosta'],
  'wif.sosta_spostata': ['stop moved to lap {giro}, {m} compound',
                         'sosta spostata al giro {giro}, mescola {m}'],
  'wif.anticipata':
    ['Stop brought forward by {n} laps against the real strategy (l.{sosta}). Final stint {n} laps longer.',
     'Sosta anticipata di {n} giri rispetto alla strategia reale (g.{sosta}). Stint finale più lungo di {n} giri.'],
  'wif.posticipata':
    ['Stop delayed by {n} laps against the real strategy (l.{sosta}). Stint 1 extended on more worn tyres.',
     'Sosta posticipata di {n} giri rispetto alla strategia reale (g.{sosta}). Stint 1 esteso su gomma più usurata.'],
  'wif.sotto_sc':       ['⚠️ Stop simulated under a real Safety Car / VSC regime',
                         '⚠️ Sosta simulata in regime di Safety Car / VSC reale'],
  'wif.da_dove':        ['Where the numbers come from', 'Da dove vengono i numeri'],
  'wif.tg_degrado':     ['Degradation', 'Degrado'],
  'wif.tg_carburante':  ['Fuel δ₇₀', 'Carburante δ₇₀'],
  'wif.tg_su_70':       ['s over 70 kg', 's su 70 kg'],
  'wif.tg_vita':        ['Compound life', 'Vita mescola'],
  'wif.tg_soglia':      ['Overtaking threshold', 'Soglia di sorpasso'],
  'wif.tg_orizzonte':   ['Validated horizon', 'Orizzonte validato'],
  'wif.tg_giri':        ['laps', 'giri'],
  'wif.spenta':         ['off', 'spenta'],
  'wif.tg_sigillo':
    ['seal: vendor/simulatore/motore/contesto_live.json — this is the context the kernel received for THIS race. Pit-loss, neutralisations and retirements are applied by the engine and declared below, in the assumptions.',
     'sigillo: vendor/simulatore/motore/contesto_live.json — è il contesto che il kernel ha ricevuto per QUESTA gara. Pit-loss, neutralizzazioni e ritiri li applica il motore e li dichiara qui sotto, nelle assunzioni.'],
  'wif.no_braccio':     ['without the «real strategy» arm there is no gap to draw',
                         "senza il braccio «strategia vera» non c'è un distacco da disegnare"],
  'wif.linea_zero':     ['real strategy, same engine ({z} s)', 'strategia vera, stesso motore ({z} s)'],
  'wif.sosta_wif_g':    ['What-If stop (l.{giro})', 'sosta What-If (g.{giro})'],
  'wif.sopra_linea':    ['above the line = your stop loses time', 'sopra la linea = la tua sosta perde tempo'],
  'com.s_giro':         ['s/lap', 's/giro'],

  /* ========================================== feedback.html — la buca delle segnalazioni */
  'fb.occhiello':       ['Reports · The site seen from outside', 'Segnalazioni · Il sito visto da fuori'],
  'fb.titolo':          ['Tell us what is <em>wrong</em>', 'Dicci cosa <em>non va</em>'],
  'fb.sottotitolo':
    ['A number that does not add up, a chart that does not draw, a page that makes no sense, something you expected to find and is not there. Write it here: we read the reports by hand, one by one, and the ones that describe a real defect become a fix.',
     "Un numero che non torna, un grafico che non si disegna, una pagina che non si capisce, una cosa che ti aspettavi di trovare e non c'è. Scrivicelo qui: le segnalazioni le leggiamo a mano, una per una, e quelle che descrivono un difetto vero diventano una correzione."],
  'fb.di_che_cosa':     ['What is this about', 'Di che cosa si tratta'],
  'fb.tipo_rotto':      ['Something is broken', 'Qualcosa non funziona'],
  'fb.tipo_sbagliato':  ['A number is wrong', 'Un numero è sbagliato'],
  'fb.tipo_oscuro':     ['It makes no sense', 'Non si capisce'],
  'fb.tipo_manca':      ['Something is missing', 'Manca qualcosa'],
  'fb.tipo_idea':       ['An idea', "Un'idea"],
  'fb.dove':            ['Where you saw it', "Dove l'hai visto"],
  'fb.dove_ph':         ['e.g. a race page, the telemetry, the championship…',
                         'es. la pagina di una gara, la telemetria, il campionato…'],
  'fb.dove_aiuto':      ['If you got here from the footer of a page, we have already filled it in for you.',
                         "Se ci sei arrivato dal piede di una pagina, l'abbiamo già scritto noi."],
  'fb.cosa':            ['What happened', 'Che cosa è successo'],
  'fb.cosa_ph':         ['What you were doing, what you expected, what you saw instead.',
                         'Che cosa stavi facendo, che cosa ti aspettavi, che cosa hai visto invece.'],
  'fb.email':           ['Your email', 'La tua email'],
  'fb.facoltativa':     ['(optional)', '(facoltativa)'],
  'fb.email_ph':        ['only needed if you want a reply', 'serve solo se vuoi una risposta'],
  'fb.email_aiuto':
    ['We use it for one thing only: to reply to you about this report. No list, no newsletter. If you leave it empty that is fine too.',
     'La usiamo per una cosa sola: risponderti su questa segnalazione. Niente lista, niente newsletter. Se la lasci vuota va bene lo stesso.'],
  'fb.esca':            ['Do not fill in this field', 'Non compilare questo campo'],
  'fb.che_parte':       ['What leaves this page', 'Che cosa parte da qui'],
  'fb.privacy':
    ['There is nothing else: no cookie, no identifier, no browsing trail. Your IP address is not kept — a hashed fingerprint of it is held for one hour, only to stop a robot from filling the queue.',
     "Non c'è altro: nessun cookie, nessun identificativo, nessuna traccia di navigazione. Il tuo indirizzo IP non viene conservato — se ne tiene un'impronta cifrata per un'ora, solo per impedire a un robot di riempire la coda."],
  'fb.manda':           ['Send the report', 'Manda la segnalazione'],
  'fb.come_t':          ['How to write a useful report', 'Come si scrive una segnalazione utile'],
  'fb.come_l':
    ['<li><b>Where</b> — the page, and if it matters which race or which driver.</li><li><b>What you expected</b> — even if it seems obvious: it almost never is.</li><li><b>What you saw instead</b> — the wrong number, the empty box, the text that does not add up.</li>',
     '<li><b>Dove</b> — la pagina, e se serve quale gara o quale pilota.</li><li><b>Che cosa ti aspettavi</b> — anche se ti sembra ovvio: quasi mai lo è.</li><li><b>Che cosa hai visto invece</b> — il numero sbagliato, il riquadro vuoto, il testo che non torna.</li>'],
  'fb.fine_t':          ['Where it ends up', 'Che fine fa'],
  'fb.fine_p':
    ['It ends up in a queue we read by hand. There is no automatic reply and no ticket: if the report describes a reproducible defect, it becomes a fix in the code; if it describes something we decided on purpose, and you left your email, we explain why.',
     "Finisce in una coda che leggiamo a mano. Non c'è nessuna risposta automatica e nessun ticket: se la segnalazione descrive un difetto riproducibile, diventa una correzione nel codice; se descrive una cosa che abbiamo deciso apposta, e hai lasciato l'email, ti spieghiamo perché."],
  'fb.sapere_t':        ['One thing to know first', 'Una cosa da sapere prima'],
  'fb.sapere_p':
    ['The simulator on this site is <b>a game, not a prediction</b>: over the whole race the engine and «change nothing» are indistinguishable, and we say so on the pages. If a number from the simulation does not match the real race, that is not necessarily a defect. If instead a <b>data point</b> does not match the real race, that one is: write to us.',
     'Il simulatore di questo sito è <b>un gioco, non una previsione</b>: sulla gara intera il motore e «non cambiare niente» sono indistinguibili, e lo diciamo nelle pagine. Se un numero della simulazione non coincide con la gara vera, non è necessariamente un difetto. Se invece un <b>dato</b> non coincide con la gara vera, quello sì: scrivicelo.'],
  'fb.et_tipo':         ['type', 'tipo'],
  'fb.et_dove':         ['where', 'dove'],
  'fb.et_testo':        ['your message', 'il tuo messaggio'],
  'fb.et_email':        ['email', 'email'],
  'fb.et_finestra':     ['window', 'finestra'],
  'fb.et_navigatore':   ['browser', 'navigatore'],
  'fb.n_caratteri':     ['{n} characters, exactly as you wrote them', '{n} caratteri, come li hai scritti'],
  'fb.niente':          ['— nothing —', '— niente —'],
  'fb.ricevuta':        ['Received.', 'Ricevuta.'],
  'fb.protocollo_a':    ['Your report has arrived. Its reference number is ',
                         'La tua segnalazione è arrivata. Il suo numero di protocollo è '],
  'fb.protocollo_b':
    ['If you left your email we will reply; otherwise you will receive nothing — there is no automatic reply, and we did not want to pretend there was.',
     "Se hai lasciato l'email ti rispondiamo noi; altrimenti non riceverai nulla — non c'è nessuna risposta automatica, e non volevamo fingere che ci fosse."],
  'fb.non_arrivata':    ['It did not arrive.', 'Non è arrivata.'],
  'fb.testo_ancora':
    ['Your text is still in the form below: you can try again in a minute. If you would rather put it somewhere safe now, copy it.',
     'Il testo è ancora nel modulo qui sotto: puoi riprovare fra un minuto. Se preferisci metterlo al sicuro adesso, copialo.'],
  'fb.copia':           ['Copy the text', 'Copia il testo'],
  'fb.copiato':         ['Copied', 'Copiato'],
  'fb.copia_ko':        ['Copy failed: select it by hand', 'Copia non riuscita: selezionalo a mano'],
  'fb.err429':          ['Quite a few reports have already been sent from this connection in the last hour: that is the anti-robot brake. Try again later.',
                         "Da questa connessione sono già partite parecchie segnalazioni nell'ultima ora: è il freno anti-robot. Riprova più tardi."],
  'fb.err503':          ['The report inbox is not reachable right now (that is a problem on our side, not yours).',
                         'La buca delle segnalazioni non è raggiungibile in questo momento (è un problema nostro, non tuo).'],
  'fb.err400':          ['The message was not accepted as it is.', "Il messaggio non è stato accettato così com'è."],
  'fb.err0':            ['The request did not even leave: it may be the network.',
                         'La richiesta non è nemmeno partita: può essere la rete.'],
  'fb.errN':            ['The server answered with an error ({stato}).', 'Il server ha risposto con un errore ({stato}).'],
  'fb.min_caratteri':   ['Write at least {n} characters.', 'Scrivi almeno {n} caratteri.'],
  'fb.email_non_valida':['That email address does not look valid.', "L'indirizzo email non sembra valido."],
  'fb.invio_corso':     ['Sending…', 'Invio in corso…'],
  'fb.buca_chiusa':     ['The inbox is closed right now.', 'La buca è chiusa in questo momento.'],
  'fb.buca_chiusa_p':
    ['The form below works, but the report receiver is not reachable: if you write now, the message would not arrive. It is a fault on our side and we are already looking at it.',
     'Il modulo qui sotto funziona, ma la ricezione delle segnalazioni non è raggiungibile: se scrivi adesso, il messaggio non arriverebbe. È un guasto nostro e lo stiamo già vedendo.'],

  /* ==================================================== gara.html — la pagina-gara */
  'gara.stagione_2026': ['2026 Season', 'Stagione 2026'],
  'gara.aria_mappa':    ['Map of the circuit with the position of the cars',
                         'Mappa del circuito con la posizione delle vetture'],
  'gara.play':          ['Play', 'Play'],
  'gara.aria_giro':     ['Lap', 'Giro'],
  'gara.torna_replay':  ['Back to the real replay', 'Torna al replay reale'],
  'gara.onesta':
    ['With <b>PIT NOW</b> the race restarts from here with your stop, all the way to the flag. The rivals make the stops they actually made: that is <b>information from the future</b>, so it is a recalculation on a race already run and <b>not a prediction</b>.',
     'Con <b>BOX ORA</b> la gara riparte da qui con la tua sosta, fino alla bandiera. I rivali fanno le soste che hanno fatto davvero: è <b>informazione dal futuro</b>, quindi un ricalcolo su una gara già corsa e <b>non una previsione</b>.'],
  'gara.per_chi':       ['Whose strategy are you calling?', 'Per chi fai la strategia?'],
  'gara.per_chi_p':
    ['Pick the driver: from here on their stops are yours to decide. The ones they actually made stay only as a comparison, at the flag.',
     'Scegli il pilota: da qui in avanti le sue soste le decidi tu. Quelle che ha fatto davvero restano solo come confronto, alla bandiera.'],
  'gara.ripiego':       ['There is no data for {chiesta} yet: this is {qui}.',
                         "Di {chiesta} non ci sono ancora i dati: qui c'è {qui}."],
  'gara.non_parte':     ['did not start', 'non parte'],
  'gara.ritirato':      ['retired', 'ritirato'],
  'gara.pista_bagnata': ['wet track', 'pista bagnata'],
  'gara.pista_asciutta':['dry track', 'pista asciutta'],
  'gara.in_gara':       ['{n} running', '{n} in gara'],
  'gara.sosta_vera_g':  ['real stop: lap {n}', 'sosta vera: giro {n}'],
  'gara.sosta_tua_g':   ['your stop: lap {n}', 'la tua sosta: giro {n}'],
  'gara.cambia_pilota': ['Change driver', 'Cambia pilota'],
  'gara.nessuna_risposta': ['For this race the engine has no ready answer.',
                            'Per questa gara il motore non ha una risposta pronta.'],
  'gara.f_non_partito': ['did not start', 'non è partito'],
  'gara.f_ritirato':    ['retired', 'si è ritirato'],
  'gara.muto_fuori':    ['{chi} {come} in this race: there is no race of theirs to replay.',
                         "{chi} {come} in questa gara: non c'è una sua gara da rigiocare."],
  'gara.muto_presto':
    ['On lap {giro} the race cannot be read yet: a few laps of pace are needed before it can answer.',
     'Al giro {giro} la gara non è ancora leggibile: serve qualche giro di passo prima di poter rispondere.'],
  'gara.muto_tardi':
    ['On lap {giro} there is too little left to the flag for a stop to have an answer.',
     'Al giro {giro} manca troppo poco alla bandiera perché fermarsi abbia una risposta.'],
  'gara.muto_tua_gara':
    ['On lap {giro} the engine cannot answer on your race: try a few laps further on.',
     'Al giro {giro} il motore non sa rispondere sulla tua gara: prova qualche giro più avanti.'],
  'gara.muto_qui':      ['At this lap the engine does not answer for {chi}.',
                         'A questo giro il motore non risponde per {chi}.'],
  'gara.vai_al_giro':   ['Go to lap {n}', 'Vai al giro {n}'],
  'gara.tit_fuori':     ["{chi} {come}: there is no race of theirs to replay",
                         "{chi} {come}: non c'è una sua gara da rigiocare"],
  'gara.tit_presto':    ['The engine answers from a few laps further on',
                         'Il motore risponde da qualche giro più avanti'],
  'gara.tit_tardi':     ['Too late for a stop to have an answer',
                         'Troppo tardi perché una sosta abbia una risposta'],
  'gara.tit_qui':       ['At this lap the engine has no answer for {chi}',
                         'A questo giro il motore non ha una risposta per {chi}'],
  'gara.e_cong':        [' and ', ' e '],
  'gara.tua_gara_1':    ['On your race: {chi} with your stop on lap {giri}.',
                         'Sulla tua gara: {chi} con la tua sosta al giro {giri}.'],
  'gara.tua_gara_n':    ['On your race: {chi} with your stops on laps {giri}.',
                         'Sulla tua gara: {chi} con le tue soste al giro {giri}.'],
  'gara.gara_vera':     ['On the real race. Press PIT NOW and the engine starts answering on yours.',
                         'Sulla gara vera. Premi BOX ORA e il motore comincia a rispondere sulla tua.'],
  'gara.gara_finita':   ['The race is over. Press ↺ to go back to the replay and redo the strategy from the start.',
                         'La gara è finita. Premi ↺ per tornare al replay e rifare la strategia da capo.'],
  'gara.senza_passo':   ['The engine has no pace yet for {chi}: try a few laps further on.',
                         'Il motore non ha ancora un passo per {chi}: prova qualche giro più avanti.'],
  'gara.scena_ko':      ['The engine cannot stage this stop: try another lap or another tyre.',
                         "Il motore non riesce a mettere in scena questa sosta: prova un altro giro o un'altra gomma."],
  'gara.piano_ko':      ['Invalid plan: try another lap or another tyre.',
                         "Piano non valido: prova un altro giro o un'altra gomma."],
  'gara.scena_assente': ['The scene is not available for this strategy.',
                         'La scena non è disponibile per questa strategia.'],
  'gara.nessuna_sosta': ['no stop', 'nessuna sosta'],
  'gara.piano_1':       ['{chi}: one stop — {piano}. The race carries on to the flag: change the speed to follow it, and press PIT NOW again to add another.',
                         '{chi}: una sosta — {piano}. La gara continua fino alla bandiera: cambia velocità per seguirla, e premi di nuovo BOX ORA per aggiungerne un\'altra.'],
  'gara.piano_n':       ['{chi}: {n} stops — {piano}. The race carries on to the flag: change the speed to follow it, and press PIT NOW again to add another.',
                         '{chi}: {n} soste — {piano}. La gara continua fino alla bandiera: cambia velocità per seguirla, e premi di nuovo BOX ORA per aggiungerne un\'altra.'],
  'gara.com_e_finita':  ['how it ended', "com'è finita"],
  'gara.nella_gara_vera': ['in the real race', 'nella gara vera'],
  'gara.ritirato_al_giro':['retired on lap {n}', 'ritirato al giro {n}'],
  'gara.strategia_vera_motore': ['real strategy in the engine', 'strategia vera nel motore'],
  'gara.direttore_no':  ['the Director does not sign this run: no comparison',
                         'il Direttore non firma questo run: niente confronto'],
  'gara.stesse_soste':  ['the same stops, replayed', 'le stesse soste, rigiocate'],
  'gara.la_tua_strategia': ['your strategy', 'la tua strategia'],
  'gara.scarto_nullo':  ['The first two boxes say how well the engine does on its own.',
                         'Le prime due caselle dicono quanto il motore ci prende da solo.'],
  'gara.scarto_su_1':   ['Your move is worth {n} position over the real strategy, engine against engine.',
                         'La tua mossa vale {n} posizione sulla strategia vera, motore contro motore.'],
  'gara.scarto_su_n':   ['Your move is worth {n} positions over the real strategy, engine against engine.',
                         'La tua mossa vale {n} posizioni sulla strategia vera, motore contro motore.'],
  'gara.scarto_giu_1':  ['The real strategy was worth {n} position more than yours, engine against engine.',
                         'La strategia vera valeva {n} posizione in più della tua, motore contro motore.'],
  'gara.scarto_giu_n':  ['The real strategy was worth {n} positions more than yours, engine against engine.',
                         'La strategia vera valeva {n} posizioni in più della tua, motore contro motore.'],
  'gara.scarto_pari':   ['Same finish as the real strategy, engine against engine.',
                         'Stesso arrivo della strategia vera, motore contro motore.'],
  'gara.nota_1':        ["The first box is the race as it went; the second is the same strategy inside the engine.",
                         "La prima casella è la gara com'è andata; la seconda è la stessa strategia dentro il motore."],
  'gara.nota_2':        ['Comparing the second with the third is the only honest comparison: only your move changes.',
                         "Confrontare la seconda con la terza è l'unico paragone onesto: cambia solo la tua mossa."],
  'gara.nota_conteggio':['The two engine boxes count {sim} drivers finishing; the real race classifies {vera}, retirements included.',
                         'Le due caselle del motore contano {sim} piloti arrivati; la gara vera ne classifica {vera}, ritirati compresi.'],

  /* ============================================ strategia.mjs — il pannello */
  'strat.aria_curva':   ['Cost of the stop per lap, from lap {da} to {a}. Best: lap {best}.',
                         'Costo della sosta per giro, dal giro {da} al {a}. Migliore: giro {best}.'],
  'strat.come_finisce': ['How it ends', 'Come finisce'],
  'strat.n_sosta_1':    ['{n} stop', '{n} sosta'],
  'strat.n_sosta_n':    ['{n} stops', '{n} soste'],
  'strat.nota_soste':   ['The finishing position, if from here on you make that number of stops.',
                         'La posizione al traguardo, se da qui in avanti fai quel numero di soste.'],
  'strat.se_ti_fermi':  ['If you pit on lap {n}', 'Se ti fermi al giro {n}'],
  'strat.su_n_in_pista':['of {n} on track', 'su {n} in pista'],
  'strat.banda':        ['likely between {da} and {a}', 'verosimile tra {da} e {a}'],
  'strat.rientri_al_giro': ['You rejoin the track on lap {n}.', 'Rientri in pista al giro {n}.'],
  'strat.al_giro_rientro': ['per lap, the moment you rejoin', 'al giro, appena rientri'],
  'strat.tiene_giri':   ['The <b>{m}</b> lasts {n} laps before it drops off.',
                         'La <b>{m}</b> tiene {n} giri prima di calare.'],
  'strat.nessuno':      ['nobody', 'nessuno'],
  'strat.davanti':      ['ahead', 'davanti'],
  'strat.dietro':       ['behind', 'dietro'],
  'strat.quando_fermarsi': ['When to pit', 'Quando fermarsi'],
  'strat.momento_migliore': ['The best moment is <b>lap {n}</b>.', 'Il momento migliore è il <b>giro {n}</b>.'],
  'strat.finestra':     ['Between lap {da} and {a} it changes little: that is the window.',
                         'Fra il giro {da} e il {a} cambia poco: è la finestra.'],
  'strat.perdita_box':  ['Pit loss', 'Perdita ai box'],
  'strat.monti':        ['You fit', 'Monti'],
  'strat.sotto_sc':     ['Under the safety car, stopping costs a lot less.',
                         'Con la safety car fermarsi costa molto meno.'],
  'strat.sotto_vsc':    ['Under the virtual safety car, stopping costs a little less.',
                         "Con la virtual safety car fermarsi costa un po' meno."],
  'strat.aria_mescole': ['Which tyre to fit', 'Che gomma montare'],
  'strat.gia_su_title': ['This is the tyre they have on now: fitting it again means finishing the race on a single compound',
                         'È la gomma che ha su adesso: rimontarla significa finire la gara su una mescola sola'],
  'strat.ce_lhai_su':   ['on the car', "ce l'hai su"],

  /* ================================== ese_vista.mjs — il rigioca dentro la pagina-gara */
  'ese.togli_sosta':    ['remove this stop', 'togli questa sosta'],
  'ese.giro_sp':        ['lap ', 'giro '],
  'ese.sostituite':
    ['({n} real stop(s) had a non-slick or unknown tyre: this starts on MEDIUM, change it yourself)',
     '({n} sosta/e vera/e montava gomma non-slick o ignota: qui parte MEDIUM, cambiala tu)'],
  'ese.dal_lapchart':   ['from the lap chart (without post-race penalties)',
                         'dal lap chart (senza penalità post-gara)'],
  'ese.la_tua':         ['YOUR strategy · in the engine', 'la TUA strategia · nel motore'],
  'ese.pos_su_1':       ['{n} position on the real plan (engine against engine)',
                         '{n} posizione sul piano vero (motore contro motore)'],
  'ese.pos_su_n':       ['{n} positions on the real plan (engine against engine)',
                         '{n} posizioni sul piano vero (motore contro motore)'],
  'ese.pos_giu_1':      ['{n} position on the real plan (engine against engine)',
                         '{n} posizione sul piano vero (motore contro motore)'],
  'ese.pos_giu_n':      ['{n} positions on the real plan (engine against engine)',
                         '{n} posizioni sul piano vero (motore contro motore)'],
  'ese.pos_pari':       ['same finish as the real plan (engine against engine)',
                         'stesso arrivo del piano vero (motore contro motore)'],
  'ese.rit_title':      ['retired in the real race: leaves the simulation on their lap',
                         'ritirato nella gara vera: esce dalla simulazione al suo giro'],
  'ese.rit_vero':       ['real', 'vero'],
  'ese.torre_nota':
    ['Order by simulated time at the flag; lapping is not modelled. The arrow compares with the real finish. Whoever retired in the real race leaves the simulation on their lap (RIT rows): a retirement is a fact, and a finish that never happened is not projected.',
     "Ordine per tempo simulato alla bandiera; i doppiaggi non sono modellati. La freccia confronta con l'arrivo reale. Chi si ritirò nella gara vera esce dalla simulazione al suo giro (righe RIT): il ritiro è un dato, non si proietta un arrivo mai successo."],
  'ese.fuori_sim':      ['Outside the simulation (no pace, rule 6): {chi}.',
                         'Fuori simulazione (senza passo, regola 6): {chi}.'],
  'ese.senza_passo':    ['on lap {n} the driver has no base pace',
                         'al giro {n} il pilota non ha un passo base'],
  'ese.senza_passo_verdi': ['on lap {n} the driver has no base pace yet (not enough green laps)',
                            'al giro {n} il pilota non ha ancora un passo base (giri verdi insufficienti)'],

  'tele.nastro_aria':   ['Track coloured by speed', 'Tracciato colorato dalla velocità'],

  /* ==================================== live_bylap.mjs — perche' il muretto tace */
  'lbl.nessun_giro':    ['no lap completed yet', 'nessun giro ancora completato'],
  'lbl.per_drv':        ['(for {chi}: {n}/3 laps completed)', '(per {chi}: {n}/3 giri completati)'],
  'lbl.passo_base':     ['base pace available for {n} drivers out of {tot}: 3 clean laps each are needed',
                         'passo-base disponibile per {n} piloti su {tot}: servono 3 giri verdi a testa'],

  'gara.motore_fermo':  ['the engine has stopped', "il motore si e' fermato"],
  'gara.non_leggibile': ['your race cannot be read yet', "la tua gara non e' ancora leggibile"],

  // «22g» = ventidue giri di gomma. Una lettera sola, ma e' l'iniziale di una parola.
  'com.g_sigla':        ['l', 'g'],

};
